### ISSUE TITLE
Example file?

### ISSUE THREAD

**Issue by saskra** [rlichtenwalter/mRMR#1]
Is it possible to provide a small toy example? For example I am wondering how to format my input file, currently it looks like that:

```
Class,f1,f2,f3,...
2,236432.0283,10734.80089,403899.139
2,268311.6713,16047.0898,480746.0285
2,273036.9338,14640.56709,451720.3672
2,259769.1156,25957.11897,414723.1245
2,293445.6201,20009.28208,457957.967
2,233897.5317,18004.15151,338560.9224
2,304474.4254,22450.29259,443437.309
1,110916.2286,42055.95477,3866734.609
1,127235.2357,33883.33067,3482291.13
1,156927.8094,37390.5515,2636100.025
1,141650.6519,48998.13556,2864093.868
1,127707.6032,58833.52719,3297159.141
1,129534.684,73803.55167,2277034.988
```

**Comment by rlichtenwalter** [comment]
Hi,

Yes, I will add examples in the next day or two.

Regards,

Ryan

**Comment by rlichtenwalter** [comment]
Hi again,

Please take a look and let me know if it's clear enough. If you think I
should add more or clarify in any way, do please let me know.

Please note that project structure changed.

Regards,

Ryan

**Comment by saskra** [comment]
Thanks a lot!
